export const transaksiList = [
  {
    id: 1,
    pelanggan: "Budi",
    layanan: "Refleksi 60 Menit",
    tanggal: "2025-10-28",
    therapist: "Rina",
    harga: 120000,
    status: "Selesai",
  },
  {
    id: 2,
    pelanggan: "Siti",
    layanan: "Refleksi 90 Menit",
    tanggal: "2025-10-28",
    therapist: "Andi",
    harga: 150000,
    status: "Proses",
  },
  {
    id: 3,
    pelanggan: "Agus",
    layanan: "Pijit Punggung",
    tanggal: "2025-10-28",
    therapist: "Maya",
    harga: 100000,
    status: "Batal",
  },
  {
    id: 4,
    pelanggan: "Dewi",
    layanan: "Refleksi Kaki 45 Menit",
    tanggal: "2025-10-27",
    therapist: "Wati",
    harga: 90000,
    status: "Selesai",
  },
  {
    id: 5,
    pelanggan: "Rudi",
    layanan: "Pijit Seluruh Badan 90 Menit",
    tanggal: "2025-10-27",
    therapist: "Bayu",
    harga: 170000,
    status: "Selesai",
  },
  {
    id: 6,
    pelanggan: "Lina",
    layanan: "Refleksi 60 Menit",
    tanggal: "2025-10-26",
    therapist: "Rina",
    harga: 120000,
    status: "Proses",
  },
  {
    id: 7,
    pelanggan: "Anton",
    layanan: "Pijit Punggung",
    tanggal: "2025-10-26",
    therapist: "Andi",
    harga: 100000,
    status: "Selesai",
  },
  {
    id: 8,
    pelanggan: "Yuni",
    layanan: "Refleksi 90 Menit",
    tanggal: "2025-10-25",
    therapist: "Maya",
    harga: 150000,
    status: "Selesai",
  },
  {
    id: 9,
    pelanggan: "Tono",
    layanan: "Pijit Kombinasi",
    tanggal: "2025-10-25",
    therapist: "Bayu",
    harga: 180000,
    status: "Batal",
  },
  {
    id: 10,
    pelanggan: "Fitri",
    layanan: "Refleksi 60 Menit",
    tanggal: "2025-10-24",
    therapist: "Wati",
    harga: 120000,
    status: "Selesai",
  },
  {
    id: 11,
    pelanggan: "Adi",
    layanan: "Pijit Punggung",
    tanggal: "2025-10-24",
    therapist: "Andi",
    harga: 100000,
    status: "Proses",
  },
  {
    id: 12,
    pelanggan: "Nur",
    layanan: "Refleksi Kaki 45 Menit",
    tanggal: "2025-10-23",
    therapist: "Rina",
    harga: 90000,
    status: "Selesai",
  },
  {
    id: 13,
    pelanggan: "Tina",
    layanan: "Pijit Seluruh Badan 120 Menit",
    tanggal: "2025-10-23",
    therapist: "Bayu",
    harga: 200000,
    status: "Selesai",
  },
  {
    id: 14,
    pelanggan: "Hadi",
    layanan: "Refleksi 90 Menit",
    tanggal: "2025-10-22",
    therapist: "Maya",
    harga: 150000,
    status: "Batal",
  },
  {
    id: 15,
    pelanggan: "Rara",
    layanan: "Pijit Kombinasi",
    tanggal: "2025-10-22",
    therapist: "Wati",
    harga: 180000,
    status: "Selesai",
  },
];